### ISSUE TITLE
Missing GPU metrics on Pod utilizing GPUs

### ISSUE THREAD

**Issue by ddseapy** [kubecost/cost-model#287]
I'm running cost-model as a Pod and not seeing any gpu resources listed.

My node:
```yaml
  allocatable:
    cpu: "8"
    ephemeral-storage: "869249609108"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 63914004Ki
    nvidia.com/gpu: "1"
    pods: "110"
  capacity:
    cpu: "8"
    ephemeral-storage: 943196192Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 64016404Ki
    nvidia.com/gpu: "1"
    pods: "110"
```

Then when going to http://localhost:9003/costDataModel?timeWindow=1d and looking at a Pod that is utilizing nvidia gpus, I see that the "nodeName" matches the node I expect but inside the `node` section I see:
```yaml
        "gpu": "",
        "gpuName": "",
        "gpuCost": ""
```
and also see:
```yaml
      "gpureq": [
        {
          "timestamp": 0,
          "value": 0
        }
```

Is there anything that needs to be done to get GPU resources to show up?  Is kube-cost grabbing these directly from the api-server, in which case I'd expect them to match what kubectl produces?  Or is it grabbing things from kube-state-metrics?
