### ISSUE TITLE
Problem with cost frontend

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubecost/cost-model#774]
I have my kubecost cost-model successfully running in my cluster:
```
kubectl get pods -n infra -lservice=kubecost
NAME                                 READY   STATUS    RESTARTS   AGE
kubecost-exporter-794f56fbb7-kdflw   1/1     Running   0          11m
```
kubecost is listening on port 9003:
```
kubectl exec -it kubecost-exporter-794f56fbb7-kdflw -n infra -- netstat -lptun
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::9003                 :::*                    LISTEN      1/app
```

following the instruction in the [README](https://github.com/kubecost/cost-model/blob/develop/ui/README.md)
i a shell i start the proxy:
```
kubect port-forward pod/kubecost-exporter-794f56fbb7-kdflw -n infra 9090:9003
```
in another shell i start the UI
```
cd ui
npm install
npx parcel src/index.html
```

When I navigate the UI at 127.0.0.1 the UI looks like:
<img width="1662" alt="Screen Shot 2021-04-19 at 3 27 25 PM" src="https://user-images.githubusercontent.com/51684360/115311125-f6b64600-a123-11eb-926e-400c0cb717c4.png">

the dev console show the following error (CORS error):
<img width="1418" alt="Screen Shot 2021-04-19 at 3 29 50 PM" src="https://user-images.githubusercontent.com/51684360/115311212-1c434f80-a124-11eb-8f80-866262463ac3.png">

If i try the curl by hand i receive a 404:
```
curl 'http://localhost:9090/model/allocation/compute?window=6d&aggregate=namespace&step=1d&accumulate=false'
404 page not found
```

**Comment by dwbrown2** [comment]
@ltagliamonte-dd can you share how you installed kubecost?

cc @SheepGotoHeaven

**Comment by ltagliamonte-dd** [comment]
I'm using my image to support a custom prom_label for cluster_id: ltagliamonte/kubecost-cost-model:dev
The pod doesn't log any error.
kubecost is running in a deployment with the following spec:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-exporter
  labels:
    service: kubecost
    app: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kubecost
      app: exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9003"
      labels:
        service: kubecost
        app: exporter
    spec:
      serviceAccountName: kubecost-sa
      containers:
      - name: kubecost-exporter
        image: "ltagliamonte/kubecost-cost-model:dev"
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: kubecost-prom-secret
              key: TOKEN
        - name: PROMETHEUS_SERVER_ENDPOINT
          value: "https://<my_prom_endpoint>/data/metrics"
        - name: CLUSTER_ID
          value: "staging-us-west-2"
        - name: AWS_CLUSTER_ID
          value: "staging-us-west-2"
        - name: PROM_CLUSTER_ID_LABEL
          value: "k8s_cluster_id"
        - name: LOG_COLLECTION_ENABLED
          value: "false"
        - name: PRODUCT_ANALYTICS_ENABLED
          value: "false"
        - name: ERROR_REPORTING_ENABLED
          value: "false"
        - name: VALUES_REPORTING_ENABLED
          value: "false"
        - name: MAX_QUERY_CONCURRENCY
          value: "100"
        - name: KUBECOST_NAMESPACE
          value: {{ .Release.Namespace }}
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
```
