### ISSUE TITLE
Move the product 'key' in 'product-configs' be moved from a ConfigMap to a Secret

### ISSUE THREAD

**Issue by wiceywkus** [kubecost/cost-model#825]
Proposal: to help protect the product key and provide cleaner integration with other tools for managing protected data, like AWS SSM, Hashicorp Vault, etc., consider switch the 'product-configs' ConfigMap to a Secret.

gz#366

**Comment by dwbrown2** [comment]
@wiceywkus you should be able to directly supply an existing secret name! 

Ref: https://github.com/kubecost/cost-analyzer-helm-chart/blob/00f667512297abf467e270b80333adc935049ac2/cost-analyzer/values.yaml#L660

Is this helpful?

**Comment by wiceywkus** [comment]
YES!
I built a Secret.yaml like:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: productkey
  labels:
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.81.0
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
type: Opaque
data:
  productkey.json: <base64-encoded string>
```
where
<base64-encoded string>'s source was formatted like ```"{key: '<my-pkey>'}"``` and looks like ```elotsoflettersandnumbers=``` post encoding.
