### ISSUE TITLE
Savings / Breakdown show resources info per container. How does this help?

### ISSUE THREAD

**Issue by r4t8** [kubecost/cost-model#986]
As the table header below shows, I can see the savings that can be made per container.

![image](https://user-images.githubusercontent.com/94070041/141160547-e475f7fc-1228-48b3-95f2-0abe8e959f08.png)

I don't understand how one can apply the recommended RAM/CPU to a certain container.

Shouldn't this table provide the same info per POD and not per CONTAINER?

I'd really appreciate if someone can spend few minutes explaining how this exactly works. The documentation is not helpful here.

**Comment by dwbrown2** [comment]
Hi @r4t8, resource requests are actually set at the individual container level and so this view of data tries to help with those very granular insights. Here's some [docs](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) but let me know if we can share more info. Apologies I misunderstood the question.

**Comment by r4t8** [comment]
Thanks for reply, @dwbrown2.
When I go to Savings I see this menu.
![image](https://user-images.githubusercontent.com/94070041/141269189-5b4e13e6-a531-44a4-9288-7b8e9f898ad5.png)

After clicking on underlined item I was expecting to discover a list of pods that are over-provisioned and some recommendations for each pod - as the resources can be configured at pod level.

With container granularity I guess I have to figure out by myself how to update pod configuration (and that is to sum up the recommendations of all the containers in a pod, right?)

I took a look at the "savings/requestSizing" api endpoint to see if I can get some more insights. Indeed, for each controller I can see the "containers" list with all the data provided in the table on GUI, but also data per "pods" and per controller.

Initially I thought that this is what I need, but then I figure out I don't understand it. For almost all pods the target key looks like: `target: {cpuCores: 0, ramBytes: 0}`. Could you please help me better understand how to interpret the data returned by this api? I browsed the docs but they didn't help.

Thanks!

**Comment by kirbsauce** [comment]
Hi @r4t8 , can you forward along both the request and response from the API call? If you like you can email it to team@kubecost.com and reference CM986.

**Comment by kbrwn** [comment]
@r4t8 As Webb mentioned containers within pods can be assigned requests and limits therefore this is why the request sizing granularity is at the container level. Here is an example:

```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
``` 

The backing savings/requestSizing API does not perform all tasks to determine savings numbers so the data presented may not be as useful as the UI. I am not sure if there is a way to get the data you seek out of this api. Maybe @michaelmdresser can help.
